In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('C:\\Users\\HP\\Downloads\\LWDcHJitQTqoxAFD3h1K_housing - Hart Ofigwe.csv.xls')

In [3]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [5]:
df['rooms_per_household'] = df['total_rooms'] / df['households']

In [6]:
df['bedrooms_per_room'] = df['total_bedrooms'] / df['total_rooms']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   longitude            20640 non-null  float64
 1   latitude             20640 non-null  float64
 2   housing_median_age   20640 non-null  float64
 3   total_rooms          20640 non-null  float64
 4   total_bedrooms       20433 non-null  float64
 5   population           20640 non-null  float64
 6   households           20640 non-null  float64
 7   median_income        20640 non-null  float64
 8   median_house_value   20640 non-null  float64
 9   ocean_proximity      20640 non-null  object
 10  rooms_per_household  20640 non-null  float64
 11  bedrooms_per_room    20433 non-null  float64
dtypes: float64(11), object(1)
memory usage: 1.9+ MB

In [8]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [31]:
from sklearn.preprocessing import LabelEncoder

# Create a copy to avoid modifying the original DataFrame directly
df_encoded = df.copy()

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to 'ocean_proximity'
df_encoded['ocean_proximity_label_encoded'] = label_encoder.fit_transform(df_encoded['ocean_proximity'])

In [10]:
#Mapping of categories to labels
for i, category in enumerate(label_encoder.classes_):
    print(f"{category}: {i}")

<1H OCEAN: 0
INLAND: 1
ISLAND: 2
NEAR BAY: 3
NEAR OCEAN: 4

In [11]:
# Display the first few rows with the new column
display(df_encoded[['ocean_proximity', 'ocean_proximity_label_encoded']].sample(10))

      ocean_proximity  ocean_proximity_label_encoded
2962           INLAND                              1
8669       NEAR OCEAN                              4
12224          INLAND                              1
13674          INLAND                              1
1437           INLAND                              1
8623        <1H OCEAN                              0
17299      NEAR OCEAN                              4
8237       NEAR OCEAN                              4
19901          INLAND                              1
18168       <1H OCEAN                              0

In [12]:
df_encoded.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,ocean_proximity_label_encoded
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,0.146591,3
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,0.155797,3
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,0.129516,3
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,0.184458,3
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,0.172096,3

In [13]:
from sklearn.preprocessing import OneHotEncoder


df_one_hot = df.copy()

# Initialize OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False)

# Reshape the column to a 2D array as required by OneHotEncoder
encode_features = one_hot_encoder.fit_transform(df_one_hot[['ocean_proximity']])

In [14]:
# Create a DataFrame from the one-hot encoded features
ohe_df = pd.DataFrame(encode_features, columns=one_hot_encoder.get_feature_names_out(['ocean_proximity']))

# Concatenate the one-hot encoded DataFrame with the original DataFrame
df_one_hot = pd.concat([df_one_hot, ohe_df], axis=1)

df_one_hot.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,rooms_per_household,bedrooms_per_room,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY,6.984127,0.146591,0.0,0.0,0.0,1.0,0.0
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6.238137,0.155797,0.0,0.0,0.0,1.0,0.0
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY,8.288136,0.129516,0.0,0.0,0.0,1.0,0.0
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY,5.817352,0.184458,0.0,0.0,0.0,1.0,0.0
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY,6.281853,0.172096,0.0,0.0,0.0,1.0,0.0

In [15]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [16]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   longitude                      20640 non-null  float64
 1   latitude                       20640 non-null  float64
 2   housing_median_age             20640 non-null  float64
 3   total_rooms                    20640 non-null  float64
 4   total_bedrooms                 20433 non-null  float64
 5   population                     20640 non-null  float64
 6   households                     20640 non-null  float64
 7   median_income                  20640 non-null  float64
 8   median_house_value             20640 non-null  float64
 9   ocean_proximity                20640 non-null  object
 10  rooms_per_household            20640 non-null  float64
 11  bedrooms_per_room              20433 non-null  float64
 12  ocean_proximity_label_encoded  20640 non-null  int32
dtypes: float64(11), int32(1), object(1)
memory usage: 2.0+ MB

In [17]:
X = df_encoded[['longitude', 'latitude', 'housing_median_age', 'total_rooms','total_bedrooms', 'population',
                'households', 'median_income', 'rooms_per_household','bedrooms_per_room','ocean_proximity_label_encoded',]]

y = df_encoded['median_house_value']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

Shape of X: (20640, 11)
Shape of y: (20640,)

In [18]:
model = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('model', DecisionTreeRegressor(
        max_depth=10,
        min_samples_split=20,
        min_samples_leaf=10,
        random_state=42,
    ))
])

model.fit(X_train, y_train)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('model',
                 DecisionTreeRegressor(max_depth=10, min_samples_leaf=10,
                                       min_samples_split=20,
                                       random_state=42))])

In [19]:
y_pred_train = model.predict(X_train)
print(y_pred_train)

[128976.47058824 392952.88888889 257930.97707736 ... 241600.
 279541.71024735 271908.33333333]

In [20]:
results_df = pd.DataFrame({'Actual': y_train, 'Predicted': y_pred_train})
display(results_df.head(10))

         Actual      Predicted
14196  103000.0  128976.470588
8267   382100.0  392952.888889
17445  172600.0  257930.977077
14265   93400.0  121014.655172
2271    96500.0   97665.217391
17848  264800.0  327446.700000
6252   157300.0  183252.317881
9389   500001.0  431946.384615
6113   139800.0  147246.666667
6061   315600.0  279541.710247

In [21]:
y_pred_test = model.predict(X_test)
print(y_pred_test)

[ 56934.54878049  72902.4291498  497719.85714286 ... 500001.
  72902.4291498  198635.29411765]

In [22]:
results_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_test})
display(results_df.head(10))

         Actual      Predicted
20046   47700.0   56934.548780
3024    45800.0   72902.429150
15663  500001.0  497719.857143
20484  218600.0  279541.710247
9814   278000.0  257930.977077
13311  158700.0  176151.388889
7113   198200.0  205884.717647
7668   157500.0  187320.289855
18246  340000.0  257930.977077
5723   446600.0  487619.500000

In [23]:
train_r2 = r2_score(y_train, y_pred_train)
test_r2 = r2_score(y_test, y_pred_test)

train_mae = mean_absolute_error(y_train, y_pred_train)
test_mae = mean_absolute_error(y_test, y_pred_test)

print("Training R² Score:", round(train_r2, 4))
print("Test R² Score:", round(test_r2, 4))

print("Training MAE:", round(train_mae, 2))
print("Test MAE:", round(test_mae, 2))

Training R² Score: 0.8171
Test R² Score: 0.735
Training MAE: 33272.41
Test MAE: 38972.93

In [29]:
param_grid = {
    'model__max_depth': [5, 10, 15, 20],
    'model__min_samples_split': [5, 10, 20],
    'model__min_samples_leaf': [5, 10, 20]}

In [25]:
from sklearn.model_selection import GridSearchCV

In [30]:
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    n_jobs=-1)

In [27]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('imputer',
                                        SimpleImputer(strategy='median')),
                                       ('model',
                                        DecisionTreeRegressor(max_depth=10,
                                                              min_samples_leaf=10,
                                                              min_samples_split=20,
                                                              random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [5, 10, 15, 20],
                         'model__min_samples_leaf': [5, 10, 20],
                         'model__min_samples_split': [5, 10, 20]},
             scoring='r2')

In [28]:
print("Best hyperparameters:", grid_search.best_params_)
print("Best CV score:", grid_search.best_score_)

Best hyperparameters: {'model__max_depth': 15, 'model__min_samples_leaf': 20, 'model__min_samples_split': 5}
Best CV score: 0.7362796252359048